#!/bin/sh
#	AIX - spezifische Anpassung
#	(c) 1999 Erich Frühstück
#	A-3423 St.Andrä/Wördern, Südtirolergasse 17-21/5

#	CC	C-Kompiler
#	maxmem	Verfügbarer Hauptspeicher
#	defsh	Default Shell für Skripts

CC="xlc -qsrcmsg -D_ALL_SOURCE"

MAXMEM=`lsdev -C -c memory | awk '
{ mem += $4 }
END { printf("%d\n", mem) }'`
