/*
:*:	main header for EFEU-Libraries
:de:	Basiskopfdatei für EFEU-Programme

$Header <EFEU/$1>

$Note
:*:
This file is createt from template on installation.
It contains system specific adjustments. Do not edit this file,
edit |@SRC@| instead.
:de:
Diese Datei wurde aus der Schablone während der Installation generiert.
Sie enthält systemspezifische Anpassungen. Änderungen sollten nicht hier,
sondern in |@SRC@| vorgenommen werden.

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

#ifndef EFEU_config_h
#define EFEU_config_h	1

#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

#ifndef	NULL
#define	NULL	(void *) 0
#endif

@eval typedef size_t unsigned long

@beg -x error "Byteorder not identified."
int x = 1;
printf("#undef	REVBYTEORDER\n");
printf("#define	REVBYTEORDER %d\n", ((char *) &x)[0]);
@end

#endif	/* EFEU/config.h */
