/*	Standardfehlermeldungen der Zeitreihen - Programmbibliothek
	(c) 1997 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6

	Version 1.0
*/

1	$!: Zeitreihenindex nicht kompatibel: $1 - $2.\n
2	$!: Unbekannter Indextype $1.\n
3	$!: Zeitreihenkonvertierung nicht zulässig.\n

11	$!: Zeitreihenindex außerhalb des zulässigen Bereichs.\n
12	$!: Zeitreihenkonvertierung nicht durchführbar.\n

21	$!: Zeitreihenfunktion ist nicht definiert.\n
22	$!: Zeitreihenausdruck: Rechtes Argument ist nicht definiert.\n
23	$!: Zeitreihenausdruck: Zeitreihenindex nicht kompatibel.\n
24	$!: Zeitreihenausdruck: Funktion ist nicht definiert.\n

31	$!: OLS: Keine Exogene Variable angegeben.\n
32	$!: OLS: Zeitreihenindex nicht kompatibel.\n
33	$!: OLS: Zuwenig Freiheitsgrade.\n
34	$!: OLS: Schätzmatrix ist Singulär.\n

41	$!: Projektion: Inkompatible Parameterzahl.\n
42	$!: Projektion: Zeitreihenindex nicht kompatibel.\n
