/*
Standardfehlermeldungen der Zeitreihen - Programmbibliothek

$Copyright (C) 1997 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: time index not compatible: $1 - $2.\n
2	$!: unknown index type $1.\n
3	$!: conversion of time series is not permitted.\n

11	$!: time index out of bound.\n
12	$!: conversion of time series is not possible.\n

21	$!: function for time series is not defined.\n
22	$!: expression of time series: right argument is not defined.\n
23	$!: expression of time series: time series not compatible.\n
24	$!: expression of time series: function not defined.\n

31	$!: OLS: missing exogene varaiable.\n
32	$!: OLS: time index not compatible.\n
33	$!: OLS: to less degrees of freedom.\n
34	$!: OLS: singulary estimation.\n

41	$!: interpolation: wrong number of parameters.\n
42	$!: interpolation: time index not compatible.\n
