/*
error messages for d2u

$Copyright (C) 2004 Erich Frühstück
This file is part of EFEU.

EFEU is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

EFEU is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with EFEU; see the file COPYING.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

conv	$1: file successful converted.\n
check	$1: conversion proposed.\n
isunix	$1: already a UNIX text file.\n
isdos	$1: already a MS-DOS text file.\n
isdir	$1: directory skipped.\n
binary	$1: binary file skiped.\n
errout	$1: output error, file not changed.\n
notmp	$1: no temporary name availabel.\n

