/*	Fehlermeldungen für Datenbankfiles
	(c) 1995 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6
*/

1	$!: Datenfile $0: Lesen nicht möglich.\n
2	$!: Datenfile $0: Ausgabe nicht möglich.\n
3	$!: Datenfile $0: Ausgabefehler.\n
4	$!: $0: Ungültige Satzlänge.\n
5	$!: $0: Fehler im Satzlängenfeld.\n

11	$!: Spalte $0: Ungültige Ziffer $1 in Zahlenwert.\n
12	$!: Spalte $0: Fehler in BCD-Wert (HIGH)\n
13	$!: Spalte $0: Fehler in BCD-Wert (LOW)\n
14	$!: Spalte $0: Fehler in BCD-Wert (SIGNUM).\n
15	$!: Spalte $0: Zeichen $1 nicht alphanumerisch.\n

31	$!: $0: tempnam() fehlgeschlagen.\n
32	$!: $0: Ausgabefehler in Datei $1: Nur $1 von $2 Sätzen ausgegeben.\n
33	$!: $0: Mehr als 8 Dateien können nicht gemischt werden.\n
