/*
error messages for database files

$Copyright (C) 1995 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: can not read from file $0.\n
2	$!: can not write to file $0.\n
3	$!: file $0: output error.\n
4	$!: $0: invalid record size.\n
5	$!: $0: error in record size field.\n

11	$!: column $0: invalid digit $1 in value.\n
12	$!: column $0: error in BCD-value (HIGH)\n
13	$!: column $0: error in BCD-value (LOW)\n
14	$!: column $0: error in BCD-value (SIGNUM).\n
15	$!: column $0: character $1 not alphanumeric.\n

31	$!: $0: tempnam() failed.\n
32	$!: $0: output error in file $1: only $1 of $2 records written.\n
33	$!: $0: can not merge more than 8 files.\n
