/*
Standardfehlermeldungen für msgtab

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: NACHRICHT $1.\n
2	$!: FEHLER $1.\n
3	$!: Formatdatei $1 nicht gefunden.\n

21	$!: Datei $1 nicht lesbar.\n
22	$!: Datei $1 nicht beschreibbar.\n
23	$!: Datei $1, Zugriff $2 nicht möglich.\n
24	$!: Schließen einer nicht mit fileopen() göffneten Datei.\n
25	$!: Verwendung einer bereits geschlossenen IO-Struktur.\n
26	$!: Temporäre Datei kann nicht generiert werden.\n

