/*
Standardfehlermeldungen der efx - Programmbibliothek

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: NACHRICHT $1.\n
2	$!: FEHLER $1.\n
3	$!: Formatdatei $1 nicht gefunden.\n

5	$!: Zuweisungstabelle ist nicht definiert.\n
6	$!: Konfigurationsdatei $1 nicht gefunden.\n
8	$!: $0: Datei $1 nicht gefunden.\n

21	$!: Datei $1 nicht lesbar.\n
22	$!: Datei $1 nicht beschreibbar.\n
23	$!: Datei $1, Zugriff $2 nicht möglich.\n
24	$!: Schließen einer nicht mit fileopen() göffneten Datei.\n
25	$!: Verwendung einer bereits geschlossenen IO-Struktur.\n
26	$!: Temporäre Datei kann nicht generiert werden.\n

27	$!: Alle temporären Dateinamen in Verwendung.\n
28	$!: Unbekannter Zugriff auf Datei.\n
29	$!: Prozess $1 nicht generierbar.\n

31	$!: Option $1 - fehlendes Argument.\n
32	$!: Unbekannte Option $1.\n
33	$!: Resourcefile $1 generiert.\n
34	$!: Initialisierungsfile $1 generiert.\n
35	$!: Datenbankindex außerhalb des zulässigen Bereichs.\n
38	$!: Variable $1 ist nicht definiert.\n
39	$!: Variable $1 kann nicht initialisiert werden (falscher Datentype).\n

41	$!: Konstanter Datenbuffer kann nicht vergrößert werden.\n
42	$!: File $0: Vorzeitiges Fileende beim Lesen eines Vektorfeldes.\n
43	$!: File $0: Ausgabefehler beim Schreiben eines Vektorfeldes.\n

60	$!: Funktion $"
61	$": Argument $1 nicht definiert.\n
62	$": Argument $1 ist kein L-Wert.\n
63	$": Zuviele Argumente.\n

65	$!: EvalFunc() mit ungültigen Datenpointer aufgerufen!\n

70	$!: Operator $1 nicht gefunden.\n
71	$!: Funktion $1 nicht gefunden.\n
72	$!: $0: Unerwartetes Zeichen $1 in Befehlszeile.\n
73	$!: Datei $1 (Suchpfad $2) nicht gefunden.\n
74	$!: Funktion $1 für Datentype $2 nicht gefunden.\n
75	$!: $1-Konstruktor für Argumentliste nicht definiert.\n

81	$!: $0: Funktions/Variablenname fehlt.\n
82	$!: $0: Funktionstype fehlt.\n
83	$!: $0: Unbekannter Datentype $1.\n
84	$!: $0: Extra Zeichen nach Ellipse $1.\n
85	$!: $0: Syntaxfehler in Ellipse $1.\n
86	$!: Vorgabewert für L-Wert nicht zulässig.\n
87	$!: Argumentliste fehlt.\n
88	$!: Argument für $1 ist kein L-Wert.\n
89	$!: $0: Objekttype fehlt.\n
90	$!: $0: Syntaxfehler im Datentype $1.\n

211	$!: Linkes Argument einer Zuweisung ist kein Objekt.\n
212	$!: Rechtes Argument einer Zuweisung ist kein Objekt.\n
213	$!: Linker Operant einer Zuweisung ist kein L-Wert.\n
214	$!: Operant des Operators $1 ist nicht definiert.\n
215	$!: Operator $1 für Datentype $2 nicht definiert.\n
216	$!: Bereichsliste: Vergleichsfunktion ist nicht definiert.\n
217	$!: Bereichsliste: Schrittweite nicht bestimmbar.\n

91	$!: Funktion $1: Kein Effekt.\n
92	$!: Funktion $1: Falsche Argumente.\n
93	$!: Funktion $1: Argument $2 ist nicht definiert.\n
94	$!: Funktion $1: Undefinierter Vorgabewert für Argument $2.\n
95	$!: $0: Ungültiger Name in for-in Schleife.\n
96	$!: $0: Funktion $1: Kein Argument für Rückgabereferenz definiert.\n
97	$!: Funktion $1: ACHTUNG: Inkompatible Rückgabereferenz.\n

101	$!: $0: Operator $1: Rechtes Argument fehlt.\n
102	$!: $0: Bedingter Ausdruck: ":" fehlt.\n
103	$!: $0: Teilterm: Abschlußklammer fehlt.\n
104	$!: $0: Ausdruck: Abschlußklammer fehlt.\n
105	$!: $0: Stringabschluß fehlt.\n
106	$!: $0: Unvollständige Argumentliste.\n
108	$!: $0: Zeichenabschluß fehlt.\n
109	$!: $0: Syntaxfehler: $1 statt $2 gelesen.\n
110	$!: $0: Syntaxfehler: unvollständiger Block.\n

111	$!: Funktion $1: Kein Effekt.\n
112	$!: Funktion $1: Falsche Argumente.\n
113	$!: $0: ACHTUNG: Kein Effekt.\n
114	$!: $0: Unerwartetes Zeichen $1.\n
115	$!: $0: Funktionsname fehlt.\n
116	$!: $0: Syntaxfehler in Funktionsdefinition $1.\n
117	$!: $0: Befehlszeile fehlt.\n
	
120	$!: Objekt vom Typ $1 wurde bereits freigegeben!\n
121	$!: $0: Unerwartetes Fileende.\n
122	$!: $0: Syntaxfehler in Strukturdefinition.\n
123	$!: $0: Syntaxfehler in Typedefinition.\n
124	$!: $0: Speichergröße von $1 ist nicht definiert.\n
125	$!: Undefiniertes Objekt $1 in Argumentliste.\n
126	$!: Undefinierter Vorgabewert in Funktionsaufruf.\n
127	$!: $0: Funktionstype fehlt.\n
128	$!: $0: Unbekannter Datentype $1.\n
129	$!: $0: Unbekannte Objektbindung in Prototype.\n

221	$!: $0: Destruktor mit Rückgabewert $1.\n
222	$!: $0: Konverter für $1 ohne Rückgabewert.\n
223	$!: $0: Argumente für Destruktor/Konverter nicht zugelassen.\n
224	$!: $0: Extra Zeichen nach void-Kennung.\n
225	$!: $0: Scope mit ungültigen Datentype $1.\n

131	$!: Zuweisung: Linkes Objekt ist kein L-Wert!\n
132	$!: Zuweisung: Rechtes Objekt ist nicht definiert!\n
133	$!: Zuweisung: Rechtes Objekt hat inkompatiblen Type!\n
134	$!: Objekt ist kein Skalar!\n
135	$!: Objekt ist kein Vektor!\n
136	$!: Objekt vom Type $1 kann nicht kopiert werden!\n
137	$!: ACHTUNG: Rekursives Objekt vom Type $1!\n
138	$!: Zusätzliche Initialisierungswerte wurden ignoriert.\n

141	$!: Unbekannter Objekttype $1.\n
142	$!: Extra Zeichen nach Ellipse $2.\n
143	$!: Vorgabewert für L-Wert nicht zulässig.\n
144	$!: Funktionsblöcke können nicht kopiert werden.\n
145	$!: Terme und Listen können nicht kopiert werden.\n
146	$!: Ellipse in Argumentliste wurde ignoriert.\n

151	$!: Variablentabelle kann nicht kopiert werden.\n
152	$!: $0: Syntaxfehler in Variablendefinition.\n
153	$!: $0: Unbekannter Datentype $1.\n
154	$!: ACHTUNG: Variable $1 neu definiert.\n
155	$!: Vektorindex außerhalb des zulässigen Bereichs.\n
156	$!: $0: Syntaxfehler in Strukturdefinition.\n
157	$!: ACHTUNG: Struktur $1 neu definiert.\n
158	$!: Speichergröße von $1 ist nicht definiert.\n
159	$!: Unerlaubtes Mitglied in Struktur $1.\n

161	$!: Objekt $1 nicht in $2 konvertierbar.\n
162	$!: Name $1 nicht gefunden.\n
163	$!: Lesefunktion für Objekt $1 nicht definiert.\n
164	$!: Objekt vom Type $1: Komponente $2 ist nicht definiert.\n
165	$!: Zuweisungsobjekt erlaubt keine Komponentenauflösung.\n
166	$!: Variable $1 ist nicht definiert.\n
167	$!: Operand von L-Wert cast ist kein L-Wert.\n

171	$!: Ungültiges "break".\n
172	$!: Ungültiges "continue".\n
173	$!: Unbekannte Funktion/Operator $1.\n
174	$!: Unbekannte Funktion/Operator $1.\n
175	$!: Funktion $1: L-Wert kann nicht generiert werden.\n

181	$!: $0: EOF in Liste.\n
182	$!: $0: Fehlendes Objekt vor $1.\n
183	$!: $0: Unerwartetes Zeichen $1 in Liste.\n
185	$!: $0: Syntaxfehler in Aufzählungsdefinition.\n
186	$!: $0: Basisklasse $1 muß ein Aufzählungstype sein.\n

191	$!: $0: Member/Scope-Name wurde nicht angegeben.\n
192	$!: $0: Komponente $1 von Scope ist nicht definiert.\n
193	$!: $0: Komponente $1 ist nicht definiert.\n
194	$!: $0: Syntaxfehler in Vektorindex.\n
195	$!: $0: Linker Operant einer Zuweisung ist kein L-Wert.\n
196	$!: $0: Global-Operator ohne Namen.\n

201	$!: Funktion "$1": Komponente von $2 bereits in Verwendung.\n
202	$!: Funktion "$1": Name bereits in Verwendung.\n
203	$!: ACHTUNG: Funktion "$1" wurde neu definiert.\n
205	$!: Funktion "$1" wurde als virtuell angenommen.\n

301	$!: Unbekannter Zufallsgeneratortype $1.\n
302	$!: Unbekannte Speicherlänge in Variablendefinition.\n

400	$!: Funktionsdefinition noch nicht ausprogrammiert.\n
401	$!: $0: Fehlender Block nach switch-Statement.\n
402	$!: $0: Syntaxfehler in case-Statement.\n
403	$!: $0: Unerwartetes Zeichen nach default-Statement.\n
404	$!: $0: Befehlszeilen vor Klausel werden ignoriert.\n

ppm	$!: $0: Ungültiger Header in Pixmap-Datei.\n
