/*
Fehlermeldungen für Dokumentformatierung

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

EFEU is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

EFEU is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with EFEU; see the file COPYING.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

0	$!: Kann aus Sicherheitsgründen von root nicht gestartet werden.\n
1	$!: Unbekannter Dokumenttype $1.\n
2	$!: $0: Unbekannte Zeichendefinition $1.\n
3	$!: Umgebung $1 ohne Abschluß.\n
4	$!: Filestatus von $1 nicht ermittelbar.\n
5	$!: Datei $1 nicht gefunden.\n

11	$!: Unbekanntes Schlüsselword $1.\n
12	$!: $0: Unbekannter Befehl \\$1.\n
13	$!: $0: Unbekannter Textmakro @$1.\n

21	$!: $0: Syntaxfehler in Befehls/Makrodefinition.\n
