/*
Formatdefinitionen zur Nullstellenbestimmung

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

2	Keine Nullstelle im Intervall [$1, $2]\n
3	$!: Maximale Stufenzahl von $(SolveStep) überschritten.\n
4	Stufe $(#1:%2d): [$2, $3]\n
5	Stufe $(#1:%2d): [$2, $3] (Gewicht: $4)\n
