/*
Formatdefinitionen für MDMATH-Funktionen

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: Leere Matrix bei Matrixinversion.\n
2	$!: Type "$1" nicht in double konvertierbar.\n
3	$!: Matrixinversion: Matrix nicht quadratisch.\n
4	$!: Matrixinversion: Datenmatrix ist singulär (dim=$1, rang=$2).\n
