/*
Fehlermeldungen der Filehilfsprogramme

$Copyright (C) 1997 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: Datei "$1": Unbekannter Zugriff "$2".\n
2	$!: $0("$1", "$2"): Ausführung fehlgeschlagen.\n
3	$!: $0("$1", "$2"): Datei kann nicht geöffnet werden.\n
4	$!: $0("$1", "$2"): Ausführung gesperrt.\n
5	$!: Temporäre Datei kann nicht generiert werden.\n
6	$!: Datei $1 nicht gefunden.\n

11	$!: Schließen einer nicht mit fileopen() göffneten Datei.\n

21	$!: File $0: Unerwartetes Fileende beim Lesen.\n
22	$!: File $0: Daten konnten nicht ausgegeben werden.\n

31	$!: $0: Temporäre Datei $1 kann nicht generiert werden.\n
32	$!: $0: Datei $1 kann nicht abgeschnitten werden.\n
33	$!: $0: Ausgabefehler in Datei $1.\n
34	$!: $0: Eingabefehler in Datei $1.\n
35	$!: $0: Filepositionierung in Datei $1 fehlgeschlagen.\n

41	$!: Datei $1.$2 nicht gefunden.\n
