/*
Fehlermeldungen für efm-Programmbibliothek

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: Konstanter Datenbuffer kann nicht vergrößert werden.\n
2	$!: File $0: Vorzeitiges Fileende beim Lesen eines Vektorfeldes.\n
3	$!: Dokumentformatierung $1 ist nicht definiert.

11	$!: $0: Datentypen sind nicht kompatibel.\n

21	$!: $0: Unbekannte Auswertungsdefintion "$1".\n
22	$!: Applikationsdatei "$1" nicht gefunden.\n

31	$!: Option -$1 - fehlendes Argument.\n
32	$!: Unbekannte Option -$1.\n
33	$!: Optionskennung -$1 ist nicht eindeutig:\n\t-$2, -$3, ...\n
34	$!: Optionskennung $1: Unzulässige Kombination\n

51	$!: $0: Mehr als ein 'u' in Ganzzahlwert.\n
52	$!: $0: Mehr als ein 'l' in Ganzzahlwert.\n

61	$!: ArgList: Unbekannte Formatanweisung $1.\n

pnoarg	$!: parsub($0): Argument $1 nicht definiert.\n
