/*
error messages for io_preproc

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

191	$!: $0: undefined directive "$1".\n
192	$!: $0: invalid character in macro argument.\n
193	$!: $0: unexpected ELIF.\n
194	$!: $0: unexpected ELSE.\n
195	$!: $0: unexpected ENDIF.\n
196	$!: $0: EOF in control block (start at line $1).\n
197	$!: $0: file "$1" not found.\n
198	$!: $0: missing filename.\n
199	$!: $0: carriage return in input file, (MSDOS file ?).\n

211	$!: WARNING: macro "$1" redefined.\n
