/*	Standardfehlermeldungen für Preprozessor
	(c) 1994 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6

	Version 0.4
*/

191	$!: $0: Unbekannte Direktive $(#1:%#s).\n
192	$!: $0: Illegales Zeichen in Makroparameter.\n
193	$!: $0: ELIF unerwartet.\n
194	$!: $0: ELSE unerwartet.\n
195	$!: $0: ENDIF unerwartet.\n
196	$!: $0: EOF in Testblock (Start bei Zeile $1).\n
197	$!: $0: Datei $(#1:%#s) wurde nicht gefunden.\n
198	$!: $0: Dateiname fehlt.\n
199	$!: $0: Wagenrücklauf in Eingabefile, (MSDOS File ?).\n

211	$!: ACHTUNG: Makro $(#1:%#s) wurde neu definiert.\n
