/*
error messages for msgtab

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: MESSAGE $1.\n
2	$!: ERROR $1.\n
3	$!: format file $1 not found.\n

21	$!: file $1 not readable.\n
22	$!: file $1 not writeable.\n
23	$!: file $1, access $2 not possible.\n
24	$!: closing a file not registered by filenotice().\n
25	$!: use of a closed IO-structure.\n
26	$!: could not create temporary file.\n

