#!/bin/sh
# :*:check TK implementation
# :de:Überprüfe die TK implementation
#
# $Copyright (C) 2002 Erich Frühstück
# This file is part of EFEU.
# 
# EFEU is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# EFEU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with EFEU; see the file COPYING.
# If not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

# get top directory (absolut path needed)

if [ $# -ge 1 ]; then
	top=$1
else
	top="../.."
fi

top=`(cd $top; pwd)`
src=`pwd`

efeuconfig update $src/config/tklib.pph $top/ppinclude/tklib.pph
