/*
error messages for efm library

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: can not expand constant data buffer.\n
2	$!: file $0: unexpected EOF by reading data field.\n
3	$!: formating type $1 is not defined.

11	$!: $0: data types not compatibel.\n

21	$!: $0: undefined funktion "$1".\n
22	$!: application file "$1" not found.\n

31	$!: option -$1 - missing argument.\n
32	$!: unknown option -$1.\n
33	$!: option key -$1 is not uniq:\n\t-$2, -$3, ...\n
34	$!: option key $1: prohibited combination\n

51	$!: $0: more then one 'u' in integral constant.\n
52	$!: $0: more then one 'l' in integral constant.\n

pnoarg	$!: parsub($0): arg $1 not defined.\n
pilkey	$!: parsub($0): illegal format key $1.\n"
imode	$!: info mode $1 not defined.\n
