/*
:*:	System specific extensions
:de:	Systemspezifische Erweiterungen

$Note
:*:
This file is createt from template on installation.
It contains system specific adjustments. Do not edit this file,
edit |@SRC@| instead.
:de:
Diese Datei wurde aus einer Schablone während der Installation generiert.
Sie enthält systemspezifische Anpassungen. Änderungen sollten nicht hier,
sondern in |@SRC@| vorgenommen werden.

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

#ifndef EFEU_extension_h
#define EFEU_extension_h	1

#include <EFEU/config.h>

@eval success HAS_ISATTY 'isatty(0)'
@eval -i sys/dir.h success HAS_GETPWNAM 'getpwnam(NULL)'

#endif	/* EFEU/extension.h */
