/*	Fehlermeldungen der Filehilfsprogramme
	(c) 1997 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6

	Version 0.4
*/

1	$!: Datei "$1": Unbekannter Zugriff "$2".\n
2	$!: $0("$1", "$2"): Ausführung fehlgeschlagen.\n
3	$!: $0("$1", "$2"): Datei kann nicht geöffnet werden.\n
5	$!: Temporäre Datei kann nicht generiert werden.\n
6	$!: Datei $1 nicht gefunden.\n

11	$!: Schließen einer nicht mit fileopen() göffneten Datei.\n

21	$!: File $0: Unerwartetes Fileende beim Lesen.\n
22	$!: File $0: Daten konnten nicht ausgegeben werden.\n

31	$!: $0: Temporäre Datei $1 kann nicht generiert werden.\n
32	$!: $0: Datei $1 kann nicht abgeschnitten werden.\n
33	$!: $0: Ausgabefehler in Datei $1.\n
34	$!: $0: Eingabefehler in Datei $1.\n
35	$!: $0: Filepositionierung in Datei $1 fehlgeschlagen.\n

41	$!: Datei $1.$2 nicht gefunden.\n
