#!/bin/sh
# :*:setting up EFEU
# :de:Basisinitialisierung von EFEU
#
# $Copyright (C) 2001 Erich Frühstück
# This file is part of EFEU.
# 
# EFEU is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# EFEU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with EFEU; see the file COPYING.
# If not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

# get top directory (absolut path needed)

if [ "$#" -ge 1 ]; then
	top=$1
else
	top="../.."
fi

src=`pwd`
top=`cd $top; pwd`

# create bin directory and expand PATH

bin=$top/bin

if [ ! -d $bin ]; then
	mkdir -p $bin || exit 1
fi

PATH=$bin:$PATH
export PATH

# preinstall config tools

sh $src/shmkmf/shmkmf.sh -r all -t $top -I $src/shmkmf $src/shmkmf/Config.make
shmkmf -r all -t $top $src/tools/Config.make
shmkmf -r all -t $top $src/efeu/Config.make

# initialize build directory

src=`cd ..; pwd`
build=$top/build
test -d $build || mkdir -p $build

cd $build
cat > Config.make << EOF
TOP=$top
SRC=$src
include efeugroup.smh
EOF

shmkmf
