/*	Fehlermeldungen für efeudoc
	(c) 1998 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6
*/

3	$!: Speichersegment konnte nicht angefordert werden.\n
4	$!: Mischbefehl $1 ist bereits definiert.\n
5	$!: Mischbefehl $1 kann nicht gelöscht werden.\n

10	$!: Konfigurationsfile $1 nicht gefunden.\n
11	$!: Eingabefile $1 nicht lesbar.\n
12	$!: Ausgabefile $1 nicht lesbar.\n
13	$!: Skriptfile $1 nicht gefunden.\n

21	$!: ACHTUNG: Umgebung $1 hat unspezifisches Ende.\n
22	$!: ACHTUNG: Umgebung $1 endet mit $2.\n
23	$!: Befehl $1 ist nicht definiert.\n
24	$!: Befehl $1 Argumente nicht zugelassen.\n
25	$!: ACHTUNG: Umgebung $1, $2 Argumente wurden ignoriert.\n

31	$!: Zeichen '%c' anstelle einer Befehlskennung gelesen.\n
32	$!: Zeichen '%c' kann nicht zurückgeschrieben werden.\n

41	$!: Testblock nicht ausgeglichen.\n
42	$!: $1, $0: Klammerung $2 ist nicht ausgeglichen.\n
43	$!: $0: Unvollständiger Block, Start bei $1.\n
44	$!: $0: Block $1 hat unspezifisches Ende.\n
45	$!: $0: Block $1 hat Abschluß $2.\n
