/*
error messages for document generator

$Copyright (C) 1999 Erich Frühstück
This file is part of EFEU.

EFEU is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

EFEU is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with EFEU; see the file COPYING.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

0	$!: Cannot be run as root (for security reasons).\n
1	$!: unknown document type $1.\n
2	$!: $0: unknown character key $1.\n
3	$!: unterminated environment $1.\n
4	$!: could not get state of file $1.\n
5	$!: file $1 not found.\n

11	$!: unknown key $1.\n
12	$!: $0: undefined command \\$1.\n
13	$!: $0: undefined macro @$1.\n

21	$!: $0: syntax error in command/macro declaration.\n
