#!/bin/sh
#	Konfigurationsfile für EFEU aktualisieren
#	(c) 2000 Erich Frühstück
#	A-3423 St.Andrä/Wördern, Südtirolergasse 17-21/5

if [ $# -ne 2 ]; then
	echo "Aufruf: $0 topdir src" >&2
	exit 1
fi

if [ ! -d $1 ]; then
	echo "$0: Bibliothek $1 existiert nicht!" >&2
fi

top=$1
src=$2
cfg=$top/etc/efeu.conf
arch=`uname -s`

if [ ! -d $top/etc ]; then
	mkdir $top/etc || exit 1
fi

#	Konfigurationsparameter bestimmen

CC=cc
MAXMEM=8
DEFSH=/bin/sh

for x in /bin/bash /local/bin/bash /bin/ksh
do
	if [ -x $x ]; then
		DEFSH=$x;
		break
	fi
done

if	[ -f $src/ARCH/$arch ]; then
	. $src/ARCH/$arch
fi

if [ -f $cfg ]; then
	. $cfg
fi

#	Shell prüfen

if [ ! -x $DEFSH ]; then
	DEFSH=$x;
	echo "$0: $DEFSH nicht verfügbar!"
	exit 1
fi

#	C-Kompiler testen

tmp=/tmp/cf$$
trap "rm -f $tmp*" 0
trap "exit 1" 1 2 3

cat > $tmp.c << !
#include <stdio.h>

int main (void)
{
#if	__STDC__
	return 0;
#else
	return 1;
#endif
}
!

$CC -o $tmp $tmp.c || { echo "$0: C-Kompiler nicht verfügbar"; exit 1; }
$tmp || { echo "$0: EFEU benötigt ANSI C-Kompiler"; exit 1; }
rm -f $tmp $tmp.c

#	Konfigurationsdatei generieren

echo "# EFEU-Konfigurationsdatei" > $cfg || exit 1
date "+# Letztes Update: %d.%m.%Y%n" >> $cfg

cat >> $cfg << !
CC="$CC"
DEFSH="$DEFSH"
MAXMEM="$MAXMEM"
!
