#!/bin/sh
#	Hauptbibliothek für EFEU bestimmen
#	(c) 2000 Erich Frühstück
#	A-3423 St.Andrä/Wördern, Südtirolergasse 17-21/5

top="/efeu"

if [ $# -ge 1 ]; then
	if [ ! -d $1 ]; then
		echo "$0: $1 existiert nicht!" >&2
		exit 1
	else
		echo $1
		exit 0
	fi
fi

for x in "" /opt /var /usr /usr/local /local
do
	if [ -d $x/efeu ]; then
		echo $x/efeu
		exit 0
	fi
done

echo "$0: Hauptbibliothek für EFEU nicht gefunden!" >&2
exit 1
