/*	Fehlermeldungen für Dokumentformatierung
	(c) 1999 Erich Frühstück
	A-3423 St.Andrä/Wördern, Südtirolergasse 17-21/5

	Version 0.6
*/

0	$!: Kann aus Sicherheitsgründen von root nicht gestartet werden.\n
1	$!: Unbekannter Dokumenttype $1.\n
2	$!: $0: Unbekannte Zeichendefinition $1.\n
3	$!: Umgebung $1 ohne Abschluß.\n
4	$!: Filestatus von $1 nicht ermittelbar.\n
5	$!: Datei $1 nicht gefunden.\n

11	$!: Unbekanntes Schlüsselword $1.\n
12	$!: $0: Unbekannter Befehl \\$1.\n
13	$!: $0: Unbekannter Textmakro @$1.\n

21	$!: $0: Syntaxfehler in Befehls/Makrodefinition.\n
