/*
Fehlermeldungen für Datenbankfiles

$Copyright (C) 1995 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

pos	$!: DBData: Feldposition $1, Breite $2 nicht zulässig (recl = $3).\n
idx	$!: DBData: Feldindex $1 nicht zulässig (dim = $2).\n

11	$!: Spalte $1: Ungültige Ziffer $2 in Zahlenwert.\n
12	$!: Spalte $1: Fehler in BCD-Wert $2 (HIGH)\n
13	$!: Spalte $1: Fehler in BCD-Wert $2 (LOW)\n
14	$!: Spalte $1: Fehler in BCD-Wert $2 (SIGNUM).\n
15	$!: Spalte $1: Zeichen $2 nicht alphanumerisch.\n

21	$!: Spalte $1: Ungültige Ziffer $2 in Zahlenwert.\n
25	$!: Spalte $1: Zeichen $2 nicht alphanumerisch.\n
