/*
Fehlermeldungen für Datenbankfiles

$Copyright (C) 1995 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: Datenfile $0: Lesen nicht möglich.\n
2	$!: Datenfile $0: Ausgabe nicht möglich.\n
3	$!: Datenfile $0: Ausgabefehler.\n
4	$!: $0: Ungültige Satzlänge.\n
5	$!: $0: Fehler im Satzlängenfeld.\n

11	$!: Spalte $0: Ungültige Ziffer $1 in Zahlenwert.\n
12	$!: Spalte $0: Fehler in BCD-Wert (HIGH)\n
13	$!: Spalte $0: Fehler in BCD-Wert (LOW)\n
14	$!: Spalte $0: Fehler in BCD-Wert (SIGNUM).\n
15	$!: Spalte $0: Zeichen $1 nicht alphanumerisch.\n

31	$!: $0: tempnam() fehlgeschlagen.\n
32	$!: $0: Ausgabefehler in Datei $1: Nur $1 von $2 Sätzen ausgegeben.\n
33	$!: $0: Mehr als 8 Dateien können nicht gemischt werden.\n
