/*
Standardfehlermeldungen der Zeitreihen - Programmbibliothek

$Copyright (C) 1997 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

1	$!: Zeitreihenindex nicht kompatibel: $1 - $2.\n
2	$!: Unbekannter Indextype $1.\n
3	$!: Zeitreihenkonvertierung nicht zulässig.\n

11	$!: Zeitreihenindex außerhalb des zulässigen Bereichs.\n
12	$!: Zeitreihenkonvertierung nicht durchführbar.\n

21	$!: Zeitreihenfunktion ist nicht definiert.\n
22	$!: Zeitreihenausdruck: Rechtes Argument ist nicht definiert.\n
23	$!: Zeitreihenausdruck: Zeitreihenindex nicht kompatibel.\n
24	$!: Zeitreihenausdruck: Funktion ist nicht definiert.\n

31	$!: OLS: Keine Exogene Variable angegeben.\n
32	$!: OLS: Zeitreihenindex nicht kompatibel.\n
33	$!: OLS: Zuwenig Freiheitsgrade.\n
34	$!: OLS: Schätzmatrix ist Singulär.\n

41	$!: Projektion: Inkompatible Parameterzahl.\n
42	$!: Projektion: Zeitreihenindex nicht kompatibel.\n
