/*	Standardfehlermeldungen der efmain - Programmbibliothek
	(c) 1994 Erich Frühstück
	A-1090 Wien, Währinger Straße 64/6

	Version 0.4
*/

1	$!: NACHRICHT $1.\n
2	$!: FEHLER $1.\n
3	$!: Formatdatei $1 nicht gefunden.\n

21	$!: Datei $1 nicht lesbar.\n
22	$!: Datei $1 nicht beschreibbar.\n
23	$!: Datei $1, Zugriff $2 nicht möglich.\n
24	$!: Schließen einer nicht mit fileopen() göffneten Datei.\n
25	$!: Verwendung einer bereits geschlossenen IO-Struktur.\n
26	$!: Temporäre Datei kann nicht generiert werden.\n

