/*
Standardfehlermeldungen für Preprozessor

$Copyright (C) 1994 Erich Frühstück
This file is part of EFEU.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; see the file COPYING.Library.
If not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
*/

191	$!: $0: Unbekannte Direktive "$1".\n
192	$!: $0: Illegales Zeichen in Makroparameter.\n
193	$!: $0: ELIF unerwartet.\n
194	$!: $0: ELSE unerwartet.\n
195	$!: $0: ENDIF unerwartet.\n
196	$!: $0: EOF in Testblock (Start bei Zeile $1).\n
197	$!: $0: Datei "$1" wurde nicht gefunden.\n
198	$!: $0: Dateiname fehlt.\n
199	$!: $0: Wagenrücklauf in Eingabefile, (MSDOS File ?).\n

211	$!: ACHTUNG: Makro "$1" wurde neu definiert.\n
